### ISSUE TITLE
Can it provide object version

### ISSUE THREAD

**Issue by hankhsiao** [webmodules/block-elements#2]
Usually we use it for checking if the element is block or not, so it is better to use an object to look up. Can you also provide object version.

**Comment by TooTallNate** [comment]
I've been on the fence about this... Array is the smallest footprint, byte-wise, so it's best to send that down the wire.

It's easy enough to convert to an Object in code, but this ends up being problematic because then many modules will be creating objects of this Array and that is wasteful, memory-wise:

```js
var blocksHash = Object.create(null);
for (var i = 0; i < blocksArray.length; i++) blocksHash[blocksArray[i]] = true;

blocksHash['BLOCKQUOTE']
// true
```

And now with ES6 it gets even more interesting, since [`Set`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) is now the idea data type for this information.

```js
var blocksSet = new Set(blocksArray);

blocksSet.has('BLOCKQUOTE');
// true
```

So that said... I'm having a hard time trying to find the balance between byte size and optimal usage/memory. One option that I'd be ok with is to leave this module as-is (exporting an Array), and then introducing a couple higher-level modules that export an Object (`block-elements-object`) or even an ES6 Set (`block-elements-set`). Thoughts?

**Comment by hankhsiao** [comment]
Thank you for the quick reply. And thank you for the program-generated list.

Some questions here.
1. Because an Array in JavaScript won't allocate a trunk of memory like traditional way, it may be implemented as an Object. So I wonder how much it will be different between an Object and an Array.
2.  You said higher-level, I will think you will require the array, and create the object based on it. Then, in this case we don't solve the memory problem.

I do agree with you to introduce modules that export an Object and Set, if they don't need to require the Array one. Make sense?

**Comment by coreh** [comment]
I would suggest `require('block-elements/hash')`, `require('block-elements/set')`, etc.

**Comment by TooTallNate** [comment]
@coreh Great idea!

**Comment by TooTallNate** [comment]
@hankhsiao @coreh Check out 1fb828e.

We're going to go with the assumption that the user's env has `Set` defined / polyfilled. I think it would still be valuable to identify this fact in the package.json file somehow (maybe `"lang": "es6"`, or by using a unique "keyword", or even something declarative like `"es6": [ "Set" ]`… There's a lot of possibilities, just trying to figure out what would be the most useful.

**Comment by hankhsiao** [comment]
@TooTallNate, thank you!
